routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// JUNIOR
Route::prefix('junior')->name('junior.')->group(function () {
    // JUNIOR INDEX
    Route::get('/', function () {
        return '<ul>
        <li><a href="'.route('junior.html').'">HTML</a></li>
        <li><a href="'.route('junior.php.index').'">PHP</a></li>
        <li><a href="'.route('junior.jquery').'">JQUERY</a></li>
    </ul>';
    });
    // JUNIOR HTML
    Route::view('/html', 'junior.html')->name('html');
    // JUNIOR JQUERY
    Route::view('/jquery', 'junior.jquery')->name('jquery');
    // JUNIOR PHP
    Route::apiResource('php', 'EmployeeController')->parameters([
        'php' => 'employee'
    ]);
});

// EXPERIENCED
Route::prefix('experienced')->name('experienced.')->group(function () {
    Route::get('transactions/data', 'TransactionController@data')->name('transactions.data');
    Route::get('transactions/rekap', 'TransactionController@rekap')->name('transactions.rekap');
    Route::resource('transactions', 'TransactionController')->except(['show', 'destroy']);
    Route::delete('transactions/detail/{detail}', 'TransactionDetailController@destroy')
        ->name('transactions.details.destroy');
});

Route::view('logika', 'logika');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use App\TransactionDetail;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\TransactionStoreRequest;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = $this->getTransactionDataQuery($request)
            ->latest('payment_date')
            ->latest('created_at');

        $transactionDetails = $query->paginate($request->per_page ?? 10);

        return view('experienced.transactions.index', compact('transactionDetails'));
    }

    /**
     * Rekap Transaksi
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function rekap(Request $request)
    {
        $query = $this->getTransactionDataQuery($request)
            ->groupBy(['payment_date', 'transaction_category_id'])
            ->latest('payment_date')
            ->select([
                'payment_date',
                'transaction_categories.name as category_name',
                DB::raw('sum(transaction_details.detail_nominal) as sum_nominal'),
            ]);

        return view('experienced.transactions.rekap', [
            'transactionDetails' => $query->paginate($request->per_page ?? 10)
        ]);
    }

    /**
     * List data transaksi
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function data(Request $request)
    {
        $query = $this->getTransactionDataQuery($request);

        $transactionDetails = $query->paginate($request->per_page ?? 10);

        return view('experienced.transactions.data', compact('transactionDetails'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('experienced.transactions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TransactionStoreRequest $request)
    {
        DB::beginTransaction();
        try {
            /** @var \App\Transaction $transaction */
            $transaction = Transaction::create($request->all());
            $detailsData = [];
            foreach ($request->details['name'] as $i => $detail_name) {
                $detailsData[] = [
                    'detail_name' => $detail_name,
                    'detail_nominal' => $request->details['nominal'][$i],
                    'transaction_category_id' => $request->details['category_id'][$i],
                ];
            }
            $transaction->details()->createMany($detailsData);
            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();
            throw $exception;
        }

        return redirect()->route('experienced.transactions.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        return view('experienced.transactions.edit', compact('transaction'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(TransactionStoreRequest $request, Transaction $transaction)
    {
        $transaction->update($request->validated());

        return redirect()->route('experienced.transactions.index');
    }

    /**
     * Build the transaction data query.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected function getTransactionDataQuery(Request $request)
    {
        return TransactionDetail::query()
            ->select(['transaction_details.*'])
            ->joinTransaction()
            ->joinTransactionCategory()
            ->when($search = $request->query('search'), function ($query) use ($search) {
                $query->where(function ($q) use ($search) {
                    $q->where('description', 'LIKE', '%'.$search.'%');
                    $q->orWhere('detail_name', 'LIKE', '%'.$search.'%');
                });
            })
            ->when($startDate = $request->query('start_date'), function ($query) use ($startDate) {
                $startDate = Carbon::createFromFormat('d/m/Y', $startDate);
                $query->whereDate('payment_date', '>=', $startDate);
            })
            ->when($endDate = $request->query('end_date'), function ($query) use ($endDate) {
                $endDate = Carbon::createFromFormat('d/m/Y', $endDate);
                $query->whereDate('payment_date', '<=', $endDate);
            })
            ->when($category = $request->query('category'), function ($query) use ($category) {
                $query->where('transaction_category_id', $category);
            });
    }
}

resources/views/experienced/transactions/create.blade.php
@extends('layouts.app')
@setOption('title', 'Input Data Transaksi')

@push('css')
<style>
.detail-transaction-table {
    border-left: 1px solid #e3e6f0;
}
.detail-transaction-table td, .detail-transaction-table th {
    border: 1px solid #e3e6f0;
}
.detail-transaction-table tr td:last-child,
.detail-transaction-table tr th:last-child {
    border-right: 0px;
    border-bottom: 0px;
    border-top: 0px;
}
</style>
@endpush

@section('content')
    <div class="card card-body shadow">
        <form action="{{ route('experienced.transactions.store') }}" method="POST" id="createTransactionForm">
            @csrf
            <div class="form-row flex-md-row-reverse justify-content-end">
                <div class="col-md-6">
                    {{-- Code --}}
                    <div class="form-group row">
                        <label for="code" class="col-sm-4 col-form-label text-md-right">Code</label>
                        <div class="col-sm-8">
                            <input id="code" name="code" type="text" class="form-control @error('code') is-invalid @enderror" value="{{ old('code') }}">
                            @error('code')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                    </div>
                    {{-- Euro Rate --}}
                    <div class="form-group row">
                        <label for="euroRate" class="col-sm-4 col-form-label text-md-right">Kurs Euro</label>
                        <div class="col-sm-8">
                            <input id="euroRate" name="euro_rate" type="number" class="form-control @error('euro_rate') is-invalid @enderror" value="{{ old('euro_rate') }}">
                            @error('euro_rate')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                    </div>
                    {{-- Payment Date --}}
                    <div class="form-group row">
                        <label for="paymentDate" class="col-sm-4 col-form-label text-md-right">Tanggal Bayar</label>
                        <div class="col-sm-8">
                            <input id="paymentDate" name="payment_date" type="date" class="form-control @error('payment_date') is-invalid @enderror" value="{{ old('payment_date') }}">
                            @error('payment_date')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="description" class="col-12 col-lg-3 col-form-label">Deskripsi</label>
                        <div class="col-12 col-lg-9">
                            <textarea name="description" id="description" cols="2" class="form-control">{{ old('description') }}</textarea>
                            @error('description')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <h3>Data Transaksi</h3>
            <div class="container" id="transactionDetails">
                @foreach (array_unique(old('details.category_id', [1])) as $category_id)
                <div class="card mb-3">
                    <div class="card-header d-flex justify-content-between">
                        <div class="form-inline flex-grow-1">
                            <label for="">Kategori</label>
                            <select type="text" class="category form-control ml-2 w-50">
                                <option value="1" {{ $category_id == 1 ? 'selected' : '' }}>Pemasukan</option>
                                <option value="2" {{ $category_id == 2 ? 'selected' : '' }}>Pengeluaran</option>
                            </select>
                        </div>
                        <button type="button" class="close text-danger">&times;</button>
                    </div>
                    <div class="card-body">
                        <table class="table detail-transaction-table mb-0">
                            <thead><tr>
                                <th>Nama Transaksi</th>
                                <th>Nominal (Rupiah)</th>
                                <th></th>
                            </tr></thead>
                            <tbody>
                                @foreach (old('details.category_id', []) as $i => $detail_category)
                                <tr>
                                    <td><input type="text" name="details[name][]" value="{{ old('details.name.'.$i) }}" class="form-control d-none">{{ old('details.name.'.$i) }}</td>
                                    <td><input type="text" name="details[nominal][]" value="{{ old('details.nominal.'.$i) }}" class="form-control d-none">{{ thousand(old('details.nominal.'.$i)) }}</td>
                                    <td>
                                        <button type="button" class="btn btn-sm btn-danger rounded-circle border-0 remove-detail-transaction-button">
                                            <i class="fas fa-sm fa-minus"></i>
                                        </button>
                                    </td>
                                </tr>
                                @endforeach
                                <tr class="add-detail-transaction-form">
                                    <td><input type="text" class="form-control form-control-sm" placeholder="nama transaksi"></td>
                                    <td><input type="number" class="form-control form-control-sm" placeholder="Rp ###.###"></td>
                                    <td>
                                        <button type="button" class="btn btn-sm btn-success rounded-circle border-0 add-detail-transaction-button">
                                            <i class="fas fa-sm fa-plus"></i>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                @endforeach
                <div class="text-right">
                    <button id="addCategoryBtn" type="button" class="btn btn-info">Tambah Kategori</button>
                </div>
            </div>
            <div class="container-fluid text-center mt-4">
                <button class="btn btn-lg btn-primary border-0 shadow px-4">Simpan</button>
                <button class="btn btn-lg btn-link text-dark">Batal</button>
            </div>
        </form>
    </div>
@endsection

@push('script')
<script>
function parseThousand(number) {
    var parts = number.toString().split(",");
    parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ".");

    return parts.join(",");
}

$(document).ready(function () {
    $('#transactionDetails input').keydown(function (e) {
        if (e.keyCode == 13) {
            e.preventDefault();
            return false;
        }
    });
    var removeDetailTransactionHandler = function (e) {
        $(e.target).closest('tr').remove();
    };
    $('.remove-detail-transaction-button').click(removeDetailTransactionHandler);
    $('.add-detail-transaction-button').click(function () {
        var $tr = $(this).closest('tr');
        var $input = $tr.find('input');
        var name = $input[0].value;
        var nominal = $input[1].value;
        if (name && nominal) {
            var newRow = '<tr>' +
                '<td><input type="text" class="d-none" name="details[name][]" value="'+name+'" readonly>'+name+'</td>' +
                '<td><input type="text" class="d-none" name="details[nominal][]" value="'+nominal+'"readonly>'+parseThousand(nominal)+'</td>' +
                '<td><button type="button" class="btn btn-sm btn-danger rounded-circle border-0 remove-detail-transaction-button">' +
                '<i class="fas fa-sm fa-minus"></i>' +
                '</button></td>' +
                '</tr>';
            $(newRow).insertBefore($tr)
                .find('.remove-detail-transaction-button').click(removeDetailTransactionHandler);
            $input.val('');
            $input[0].focus();
        } else {
            if (!$input.hasClass('is-invalid')) {
                $input.each(function (i, input) {
                    if (! input.value) {
                        $(input).addClass('is-invalid');
                    }
                });
                setTimeout(function () {
                    $input.removeClass('is-invalid');
                }, 1000);
            }
        }
    });
    $('#transactionDetails .card .card-header .close').click(function (e) {
        $(e.target).closest('.card').remove();
    });
    var $categoryCardStub = $('#transactionDetails .card').first().clone(true, true);
    $('#addCategoryBtn').click(function () {
        var $categoryCard = $categoryCardStub.clone(true, true);
        $categoryCard.find('table > tbody > tr:not(.add-detail-transaction-form)').remove();

        $categoryCard.insertBefore($(this).parent());
    });
    $('#createTransactionForm').submit(function (e) {
        e.preventDefault();
        $('#transactionDetails > .card > .card-body > .table > tbody > tr:not(:last-child)').each(function (i, row) {
            var val = $(row).closest('.card').find('option:selected').val();
            $(row).prepend(
                $('<input type="hidden" name="details[category_id][]" value="">').val(val)
            )
        });
        return e.target.submit();
    })
});
</script>
@endpush

resources/views/experienced/transactions/data.blade.php
@extends('layouts.app')
@setOption('title', 'Data Transaksi')

@push('css')
<link href="{{ asset('css/datepicker.min.css') }}" rel="stylesheet">
@endpush

@section('content')
    <div class="d-flex">
        <form action="{{ request()->fullUrl() }}" class="form-inline ml-auto">
            <input type="text" class="form-control mr-2 datepicker-here" data-language="id" name="start_date" value="{{ request('start_date') }}" placeholder="tanggal">
            <span class="mr-2">sampai</span>
            <input type="text" class="form-control mr-2 datepicker-here" data-language="id" name="end_date" value="{{ request('end_date') }}" placeholder="tanggal">
            <select id="selectCategory" class="form-control mr-2" name="category">
                <option value="">-- Semua Kategori --</option>
                @foreach (\App\TransactionCategory::all() as $category)
                <option value="{{ $category->id }}"{{ request('category') == $category->id ? ' selected' : '' }}>{{ $category->name }}</option>
                @endforeach
            </select>
            <input type="text" class="form-control mr-2" placeholder="Search" name="search" value="{{ request('search') }}">
            <button type="submit" class="btn btn-outline-primary">
                Search
            </button>
        </form>
    </div>
    <div class="card card-body shadow mt-3 p-0">
        <table class="table mb-0">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Deskripsi</th>
                    <th>Code</th>
                    <th>Rate Euro</th>
                    <th>Payment Date</th>
                    <th>Kategori</th>
                    <th>Nama Transaksi</th>
                    <th>Nominal (IDR)</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($transactionDetails as $i => $data)
                <tr>
                    <td>{{ $transactionDetails->firstItem() + $i }}</td>
                    <td>{{ $data->description }}</td>
                    <td>{{ $data->code }}</td>
                    <td>{{ thousand($data->euro_rate) }}</td>
                    <td>{{ Carbon\Carbon::parse($data->payment_date)->format('d F Y') }}</td>
                    <td>{{ $data->category_name }}</td>
                    <td>{{ $data->detail_name }}</td>
                    <td>{{ thousand($data->detail_nominal) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="justify-content-between d-flex mt-3">
        <div>
            <div class="form-group form-inline">
                <form action="{{ request()->fullUrl() }}">
                    <select name="per_page" class="form-control mr-2" style="min-width: 60px;"
                    onchange="this.form.submit()"
                    >
                        <option value="10" {{ request('per_page', 10) == 10 ? 'selected' : '' }}>10</option>
                        <option value="25" {{ request('per_page', 10) == 25 ? 'selected' : '' }}>25</option>
                        <option value="50" {{ request('per_page', 10) == 50 ? 'selected' : '' }}>50</option>
                    </select>
                    <span>Menampilkan {{ $transactionDetails->count() }} dari {{ $transactionDetails->total() }}</span>
                </form>
            </div>
        </div>
        {{ $transactionDetails->appends(request()->query())->links() }}
    </div>
@endsection

@push('script')
<script src="{{ asset('/js/datepicker.min.js') }}"></script>
<script src="{{ asset('/js/datepicker.id.js') }}"></script>
<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
@endpush

resources/views/experienced/transactions/edit.blade.php
@extends('layouts.app')
@setOption('title', 'Edit Data Transaksi')

@push('css')
<style>
.detail-transaction-table {
    border-left: 1px solid #e3e6f0;
}
.detail-transaction-table td, .detail-transaction-table th {
    border: 1px solid #e3e6f0;
}
.detail-transaction-table tr td:last-child,
.detail-transaction-table tr th:last-child {
    border-right: 0px;
    border-bottom: 0px;
    border-top: 0px;
}
</style>
@endpush

@section('content')
    <div class="card card-body shadow">
        <form action="{{ route('experienced.transactions.update', $transaction->code) }}" method="POST" id="createTransactionForm">
            @csrf @method('PUT')
            <div class="form-row flex-md-row-reverse justify-content-end">
                <div class="col-md-6">
                    {{-- Code --}}
                    <div class="form-group row">
                        <label for="code" class="col-sm-4 col-form-label text-md-right">Code</label>
                        <div class="col-sm-8">
                            <input id="code" name="code" type="text" class="form-control @error('code') is-invalid @enderror" value="{{ old('code', $transaction->code) }}">
                            @error('code')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                    </div>
                    {{-- Euro Rate --}}
                    <div class="form-group row">
                        <label for="euroRate" class="col-sm-4 col-form-label text-md-right">Kurs Euro</label>
                        <div class="col-sm-8">
                            <input id="euroRate" name="euro_rate" type="number" class="form-control @error('euro_rate') is-invalid @enderror" value="{{ old('euro_rate', $transaction->euro_rate) }}">
                            @error('euro_rate')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                    </div>
                    {{-- Payment Date --}}
                    <div class="form-group row">
                        <label for="paymentDate" class="col-sm-4 col-form-label text-md-right">Tanggal Bayar</label>
                        <div class="col-sm-8">
                            <input id="paymentDate" name="payment_date" type="date" class="form-control @error('payment_date') is-invalid @enderror" value="{{ old('payment_date', $transaction->payment_date->format('Y-m-d')) }}">
                            @error('payment_date')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="description" class="col-12 col-lg-3 col-form-label">Deskripsi</label>
                        <div class="col-12 col-lg-9">
                            <textarea name="description" id="description" cols="2" class="form-control">{{ old('description', $transaction->description) }}</textarea>
                            @error('description')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <h3>Data Transaksi</h3>
            <div class="container" id="transactionDetails">
                @foreach ($transaction->details->groupBy->transaction_category_id as $category_id => $details)
                <div class="card mb-3">
                    <div class="card-header d-flex justify-content-between">
                        <div class="form-inline flex-grow-1">
                            <label for="">Kategori</label>
                            <select type="text" class="category form-control ml-2 w-50">
                                <option value="1" {{ $category_id == 1 ? 'selected' : '' }}>Pemasukan</option>
                                <option value="2" {{ $category_id == 2 ? 'selected' : '' }}>Pengeluaran</option>
                            </select>
                        </div>
                        <button type="button" class="close text-danger">&times;</button>
                    </div>
                    <div class="card-body">
                        <table class="table detail-transaction-table mb-0">
                            <thead><tr>
                                <th>Nama Transaksi</th>
                                <th>Nominal (Rupiah)</th>
                                <th></th>
                            </tr></thead>
                            <tbody>
                                @foreach ($details as $detail)
                                <tr>
                                    <td><input type="text" name="details[name][]" value="{{ $detail->detail_name }}" class="form-control d-none">{{ $detail->detail_name }}</td>
                                    <td><input type="text" name="details[nominal][]" value="{{ $detail->detail_nominal }}" class="form-control d-none">{{ thousand($detail->detail_nominal) }}</td>
                                    <td>
                                        <button type="button" class="btn btn-sm btn-danger rounded-circle border-0 remove-detail-transaction-button">
                                            <i class="fas fa-sm fa-minus"></i>
                                        </button>
                                    </td>
                                </tr>
                                @endforeach
                                <tr class="add-detail-transaction-form">
                                    <td><input type="text" class="form-control form-control-sm" placeholder="nama transaksi"></td>
                                    <td><input type="number" class="form-control form-control-sm" placeholder="Rp ###.###"></td>
                                    <td>
                                        <button type="button" class="btn btn-sm btn-success rounded-circle border-0 add-detail-transaction-button">
                                            <i class="fas fa-sm fa-plus"></i>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                @endforeach
                <div class="text-right">
                    <button id="addCategoryBtn" type="button" class="btn btn-info">Tambah Kategori</button>
                </div>
            </div>
            <div class="container-fluid text-center mt-4">
                <button class="btn btn-lg btn-primary border-0 shadow px-4">Simpan</button>
                <button class="btn btn-lg btn-link text-dark">Batal</button>
            </div>
        </form>
    </div>
@endsection

@push('script')
<script>
function parseThousand(number) {
    var parts = number.toString().split(",");
    parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ".");

    return parts.join(",");
}

$(document).ready(function () {
    $('#transactionDetails input').keydown(function (e) {
        if (e.keyCode == 13) {
            e.preventDefault();
            return false;
        }
    });
    var removeDetailTransactionHandler = function (e) {
        $(e.target).closest('tr').remove();
    };
    $('.remove-detail-transaction-button').click(removeDetailTransactionHandler);
    $('.add-detail-transaction-button').click(function () {
        var $tr = $(this).closest('tr');
        var $input = $tr.find('input');
        var name = $input[0].value;
        var nominal = $input[1].value;
        if (name && nominal) {
            var newRow = '<tr>' +
                '<td><input type="text" class="d-none" name="details[name][]" value="'+name+'" readonly>'+name+'</td>' +
                '<td><input type="text" class="d-none" name="details[nominal][]" value="'+nominal+'"readonly>'+parseThousand(nominal)+'</td>' +
                '<td><button type="button" class="btn btn-sm btn-danger rounded-circle border-0 remove-detail-transaction-button">' +
                '<i class="fas fa-sm fa-minus"></i>' +
                '</button></td>' +
                '</tr>';
            $(newRow).insertBefore($tr)
                .find('.remove-detail-transaction-button').click(removeDetailTransactionHandler);
            $input.val('');
            $input[0].focus();
        } else {
            if (!$input.hasClass('is-invalid')) {
                $input.each(function (i, input) {
                    if (! input.value) {
                        $(input).addClass('is-invalid');
                    }
                });
                setTimeout(function () {
                    $input.removeClass('is-invalid');
                }, 1000);
            }
        }
    });
    $('#transactionDetails .card .card-header .close').click(function (e) {
        $(e.target).closest('.card').remove();
    });
    var $categoryCardStub = $('#transactionDetails .card').first().clone(true, true);
    $('#addCategoryBtn').click(function () {
        var $categoryCard = $categoryCardStub.clone(true, true);
        $categoryCard.find('table > tbody > tr:not(.add-detail-transaction-form)').remove();

        $categoryCard.insertBefore(this);
    });
    $('#createTransactionForm').submit(function (e) {
        e.preventDefault();
        $('#transactionDetails > .card > .card-body > .table > tbody > tr:not(:last-child)').each(function (i, row) {
            var val = $(row).closest('.card').find('option:selected').val();
            $(row).prepend(
                $('<input type="hidden" name="details[category_id][]" value="">').val(val)
            )
        });
        return e.target.submit();
    })
});
</script>
@endpush